name:                xcache-hs
version:             0.1.0
github:              "rinse/xcache-hs"
license:             BSD3
author:              "rinse"
maintainer:          "rinse@neko2.net"
copyright:           "2021 rinse"

extra-source-files:
- .gitignore
- LICENSE
- README.md
- package.yaml
- stack.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rinse/xcache-hs#readme>

dependencies:
- base >= 4.10 && < 5
- cryptonite
- Diff
- mtl
- optparse-applicative
- pretty
- text
- turtle
- rio

library:
  source-dirs: src

executables:
  xcache:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xcache-hs
    default-extensions:
    - NoImplicitPrelude

tests:
  xcache-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xcache-hs
    - hspec >= 2.7.0
    default-extensions:
    - NoImplicitPrelude

  xcache-hs-doctest:
    main:                Spec.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xcache-hs
    - doctest >= 0.16
    - doctest-discover >= 0.2.0
    - QuickCheck >= 2.13

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
